// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/proto/gei/session.proto

// The proto package MUST match GEI's server (package `session`) so the gRPC
// method paths line up (/session.SessionIndexer/...). The Go package is set
// separately via go_package.

package gei

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Cookie        string                 `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSessionRequest) Reset() {
	*x = StoreSessionRequest{}
	mi := &file_internal_proto_gei_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSessionRequest) ProtoMessage() {}

func (x *StoreSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gei_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSessionRequest.ProtoReflect.Descriptor instead.
func (*StoreSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gei_session_proto_rawDescGZIP(), []int{0}
}

func (x *StoreSessionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StoreSessionRequest) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

type StoreSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSessionResponse) Reset() {
	*x = StoreSessionResponse{}
	mi := &file_internal_proto_gei_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSessionResponse) ProtoMessage() {}

func (x *StoreSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gei_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSessionResponse.ProtoReflect.Descriptor instead.
func (*StoreSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gei_session_proto_rawDescGZIP(), []int{1}
}

func (x *StoreSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_internal_proto_gei_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gei_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gei_session_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Cookie        string                 `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_internal_proto_gei_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gei_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gei_session_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSessionResponse) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *GetSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_internal_proto_gei_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gei_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gei_session_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSessionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_internal_proto_gei_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gei_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gei_session_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_proto_gei_session_proto protoreflect.FileDescriptor

const file_internal_proto_gei_session_proto_rawDesc = "" +
	"\n" +
	" internal/proto/gei/session.proto\x12\asession\"I\n" +
	"\x13StoreSessionRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06cookie\x18\x02 \x01(\tR\x06cookie\"J\n" +
	"\x14StoreSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x11GetSessionRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"`\n" +
	"\x12GetSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06cookie\x18\x02 \x01(\tR\x06cookie\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"2\n" +
	"\x14DeleteSessionRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"K\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf4\x01\n" +
	"\x0eSessionIndexer\x12K\n" +
	"\fStoreSession\x12\x1c.session.StoreSessionRequest\x1a\x1d.session.StoreSessionResponse\x12E\n" +
	"\n" +
	"GetSession\x12\x1a.session.GetSessionRequest\x1a\x1b.session.GetSessionResponse\x12N\n" +
	"\rDeleteSession\x12\x1d.session.DeleteSessionRequest\x1a\x1e.session.DeleteSessionResponseB1Z/github.com/nrmnqdds/gomaluum/internal/proto/geib\x06proto3"

var (
	file_internal_proto_gei_session_proto_rawDescOnce sync.Once
	file_internal_proto_gei_session_proto_rawDescData []byte
)

func file_internal_proto_gei_session_proto_rawDescGZIP() []byte {
	file_internal_proto_gei_session_proto_rawDescOnce.Do(func() {
		file_internal_proto_gei_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_gei_session_proto_rawDesc), len(file_internal_proto_gei_session_proto_rawDesc)))
	})
	return file_internal_proto_gei_session_proto_rawDescData
}

var file_internal_proto_gei_session_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_gei_session_proto_goTypes = []any{
	(*StoreSessionRequest)(nil),   // 0: session.StoreSessionRequest
	(*StoreSessionResponse)(nil),  // 1: session.StoreSessionResponse
	(*GetSessionRequest)(nil),     // 2: session.GetSessionRequest
	(*GetSessionResponse)(nil),    // 3: session.GetSessionResponse
	(*DeleteSessionRequest)(nil),  // 4: session.DeleteSessionRequest
	(*DeleteSessionResponse)(nil), // 5: session.DeleteSessionResponse
}
var file_internal_proto_gei_session_proto_depIdxs = []int32{
	0, // 0: session.SessionIndexer.StoreSession:input_type -> session.StoreSessionRequest
	2, // 1: session.SessionIndexer.GetSession:input_type -> session.GetSessionRequest
	4, // 2: session.SessionIndexer.DeleteSession:input_type -> session.DeleteSessionRequest
	1, // 3: session.SessionIndexer.StoreSession:output_type -> session.StoreSessionResponse
	3, // 4: session.SessionIndexer.GetSession:output_type -> session.GetSessionResponse
	5, // 5: session.SessionIndexer.DeleteSession:output_type -> session.DeleteSessionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_gei_session_proto_init() }
func file_internal_proto_gei_session_proto_init() {
	if File_internal_proto_gei_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gei_session_proto_rawDesc), len(file_internal_proto_gei_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gei_session_proto_goTypes,
		DependencyIndexes: file_internal_proto_gei_session_proto_depIdxs,
		MessageInfos:      file_internal_proto_gei_session_proto_msgTypes,
	}.Build()
	File_internal_proto_gei_session_proto = out.File
	file_internal_proto_gei_session_proto_goTypes = nil
	file_internal_proto_gei_session_proto_depIdxs = nil
}
