// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: internal/proto/gei/session.proto

// The proto package MUST match GEI's server (package `session`) so the gRPC
// method paths line up (/session.SessionIndexer/...). The Go package is set
// separately via go_package.

package gei

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionIndexer_StoreSession_FullMethodName  = "/session.SessionIndexer/StoreSession"
	SessionIndexer_GetSession_FullMethodName    = "/session.SessionIndexer/GetSession"
	SessionIndexer_DeleteSession_FullMethodName = "/session.SessionIndexer/DeleteSession"
)

// SessionIndexerClient is the client API for SessionIndexer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionIndexer persists a user's i-Ma'luum session cookie (MOD_AUTH_CAS),
// encrypted at rest by GEI, so a live cookie is reused across requests and
// restarts instead of re-logging-in every time.
type SessionIndexerClient interface {
	// Store a user's session cookie (encrypted). Admin-key guarded.
	StoreSession(ctx context.Context, in *StoreSessionRequest, opts ...grpc.CallOption) (*StoreSessionResponse, error)
	// Retrieve a user's session cookie (decrypted).
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	// Delete a user's session cookie (e.g. once it is stale). Admin-key guarded.
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
}

type sessionIndexerClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionIndexerClient(cc grpc.ClientConnInterface) SessionIndexerClient {
	return &sessionIndexerClient{cc}
}

func (c *sessionIndexerClient) StoreSession(ctx context.Context, in *StoreSessionRequest, opts ...grpc.CallOption) (*StoreSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreSessionResponse)
	err := c.cc.Invoke(ctx, SessionIndexer_StoreSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionIndexerClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, SessionIndexer_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionIndexerClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, SessionIndexer_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionIndexerServer is the server API for SessionIndexer service.
// All implementations must embed UnimplementedSessionIndexerServer
// for forward compatibility.
//
// SessionIndexer persists a user's i-Ma'luum session cookie (MOD_AUTH_CAS),
// encrypted at rest by GEI, so a live cookie is reused across requests and
// restarts instead of re-logging-in every time.
type SessionIndexerServer interface {
	// Store a user's session cookie (encrypted). Admin-key guarded.
	StoreSession(context.Context, *StoreSessionRequest) (*StoreSessionResponse, error)
	// Retrieve a user's session cookie (decrypted).
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	// Delete a user's session cookie (e.g. once it is stale). Admin-key guarded.
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	mustEmbedUnimplementedSessionIndexerServer()
}

// UnimplementedSessionIndexerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionIndexerServer struct{}

func (UnimplementedSessionIndexerServer) StoreSession(context.Context, *StoreSessionRequest) (*StoreSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreSession not implemented")
}
func (UnimplementedSessionIndexerServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionIndexerServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedSessionIndexerServer) mustEmbedUnimplementedSessionIndexerServer() {}
func (UnimplementedSessionIndexerServer) testEmbeddedByValue()                        {}

// UnsafeSessionIndexerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionIndexerServer will
// result in compilation errors.
type UnsafeSessionIndexerServer interface {
	mustEmbedUnimplementedSessionIndexerServer()
}

func RegisterSessionIndexerServer(s grpc.ServiceRegistrar, srv SessionIndexerServer) {
	// If the following call pancis, it indicates UnimplementedSessionIndexerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionIndexer_ServiceDesc, srv)
}

func _SessionIndexer_StoreSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionIndexerServer).StoreSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionIndexer_StoreSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionIndexerServer).StoreSession(ctx, req.(*StoreSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionIndexer_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionIndexerServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionIndexer_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionIndexerServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionIndexer_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionIndexerServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionIndexer_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionIndexerServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionIndexer_ServiceDesc is the grpc.ServiceDesc for SessionIndexer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionIndexer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.SessionIndexer",
	HandlerType: (*SessionIndexerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreSession",
			Handler:    _SessionIndexer_StoreSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionIndexer_GetSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _SessionIndexer_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/gei/session.proto",
}
